import firebase from 'firebase/compat/app';
import 'firebase/compat/firestore';
import { load } from "./load.model";
import { status } from "./status.model";
import * as turf from '@turf/turf';

export class bid {
    id?: string;
    userId?: string;
    userCompany?: string;
    userDescription?: string;
    loadId?: string;
    loadDescription?: string;
    loadUserId?: string;
    loadLoadTypeId?: string;
    loadLoadTypeDescription?: string;
    loadNote?: string;
    loadPrice?: number;
    loadOriginatingAddress?: string;
    loadOriginatingCoordinates?: turf.Point;
    loadDestinationAddress?: string;
    loadDestinationCoordinates?: turf.Point;
    loadItemCount?: number;
    loadWeight?: number;
    loadLength?: number;
    loadWidth?: number;
    loadHeight?: number;
    loadTotalValue?: number;
    loadDateOut?: Date;
    loadDateIn?: Date;
    loadDateBidEnd?: Date;
    loadAvatar?: string
    loadStatus?: string;
    vehicleId?: string;
    vehicleDescription?: string;
    driverId?: string;
    driverDescription?: string;
    price?: number;
    dateOut?: Date;
    dateIn?: Date;
    status?: string;
    reviewLoad?: number;
    reviewLoadCount?: number;
    reviewDriver?: number;
    reviewDriverCount?: number;
    userIdAccepted?: string;
    userIdLoaded?: string;
    userIdLoadedConfirmed?: string;
    userIdDelivered?: string;
    userIdDeliveredConfirmed?: string;
}