import firebase from 'firebase/compat/app';
import 'firebase/compat/firestore';
import * as geofirestore from 'geofirestore';
import { bid } from "./bid.model";
import * as geofire from 'geofire-common';
import * as turf from '@turf/turf';

export class load {
    id?: string;
    userId?: string;
    userDescription?: string;
    loadCategoryId?: string;
    loadCategoryDescription?: string;
    loadTypeId?: string;
    loadTypeDescription?: string;
    loadTypeLiquid?: boolean;
    description?: string;
    note?: string;
    price?: number;
    originatingCoordinates?: turf.Point;
    originatingAddress?: string;
    destinationCoordinates?: turf.Point;
    destinationAddress?: string;
    route?: string;
    itemCount?: number;
    weight?: number;
    length?: number;
    width?: number;
    height?: number;
    volumeCm?: number;
    volumeLt?: number;
    totalValue?: number;
    dateOut?: Date;
    dateIn?: Date;
    dateBidEnd?: Date;
    avatar?: string;
    status?: string;
    review?: number;
    reviewCount?: number;
    bidCount?: number;
    userIdAccepted?: string;
    userIdLoaded?: string;
    userIdLoadedConfirmed?: string;
    userIdDelivered?: string;
    userIdDeliveredConfirmed?: string;
    bid?: bid[];
}